Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Huelton Santos
// Descrição   : Criar um programa para calcular a area de um círculo
// Autor(a)    : Uilian Dias Kumagai
// Data atual  : 13/01/2021
Var
// Seção de Declarações das variáveis 
 raio: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o valor do raio")
 leia(raio)
 escreval("O valor da área é: ", PI *(raio^2):2:2)

Fimalgoritmo